site_name: The Materials Project Workshop
site_description: Lessons for the Materials Project Workshop
copyright: Built by The Materials Project
site_url: https://workshop.materialsproject.org
repo_url: https://github.com/materialsproject/workshop
docs_dir: workshop
extra_css: [workshop.css]
theme:
  name: 'material'
  icon:
    logo: material/book-open-page-variant
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Logistics: logistics/logistics.md
  - People: people/people.md
  - Code of Conduct: code_of_conduct.md
  - Primer:
    - Intro: primer/01_basic_python/0 - Introduction and Jupyter Use.ipynb
    - Basic Python: primer/01_basic_python/1 - Python Primer.ipynb
    - Advanced Python: primer/02_building_logic/2 - Python Primer - Part II.ipynb
    - Intro to MongoDB: primer/03_MongoDB_part1/lessons.ipynb
    - Advanced MongoDB: primer/04_MongoDB_part2/lesson.ipynb
  - Workshop:
    - The Materials Project Website: lessons/01_website_walkthrough/website_walkthrough.md
    - Intro to Pymatgen: lessons/02_intro_pymatgen/1 - pymatgen foundations.ipynb
    - Working with Surfaces: lessons/03_surfaces/Working With Surfaces_lesson.ipynb
    - The Materials API: lessons/04_materials_api/api_use.ipynb
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.arithmatex
  - toc:
      permalink: true

plugins:
  - search
  - mknotebooks
  - minify:
      minify_html: true
